[core]
dev = "cpu"
listen_ip = "127.0.0.1" 
min_port = 1000
gpu_mem = 300 # unit: MiB

[database]
host = "127.0.0.1"
port = 3306
db = "stf"
user = "stf"
pwd = "stf"

[system.flow]
name = "FLOW"
cluster_path = "./test/a.csv"
cluster_number = 2
logdir = "./test/log/"
model_lib = "./model_instance/base_model.py"
model_paths = [
    "./test/0.h5",
    "./test/0.h5"
]